name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  ts-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test:ts:typecheck

  ts-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test:ts:node

  ts-browser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: npx playwright install --with-deps chromium
      - run: yarn test:ts:browser

  rs-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test -q --manifest-path rs/Cargo.toml

  rs-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: jetli/wasm-pack-action@v0.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: yarn test:rs:wasm

  rs-pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: ./scripts/verify-rs-pkg.sh
